### ISSUE TITLE
Menu Disappears

### ISSUE THREAD

**Issue by Elleby77** [ParkitectNexus/Parkitect-Mod-Spark#1]
I'm very new to Unity, so this might be a trivial issue.    When I add other packages in my scene that the "Parkitect" menu item disappears and I can't access the "Mod-Setup" window.

Any ideas on how to resolve this?

**Comment by H-POPS** [comment]
What do you mean by adding packages to the scene? Do you get any error messages in the console of Unity?

**Comment by Elleby77** [comment]
No error messages,  just the menu disappears.    Is there a way to manually rerun the script that adds the menu?

**Comment by H-POPS** [comment]
It is just a script that is based in the project, it should never get deleted. Can you explain exactly what you are doing when the menu item disappears?

**Comment by Elleby77** [comment]
I think it is from other packages I've imported.   Importing those without their scripts seems to solve it.

I guess it is just me being a noob with Unity.
